version: "3.8"

networks:
    tirgannet:
        driver: bridge

volumes:
    mysql-data:
        driver: local
    pma-data:
        driver: local

services:
    mysql:
        image: "${MYSQL_IMG}"
        container_name: "${MYSQL_CONTAINER_NAME}"
        restart: "${MYSQL_RESTART_MODE}"
        tty: true
        ports:
            - "${MYSQL_PORT}:3306"

        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"

        volumes:
            - "mysql-data:/var/lib/mysql"
        networks:
            - tirgannet

    phpmyadmin:
        image: "${PMA_IMAGE}"
        container_name: "${PMA_CONTAINER_NAME}"
        environment:
            # PMA_PMADB: 1
            # PMA_ARBITRARY: 1
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            PMA_HOST: "${PMA_HOST}"
            PMA_PORT: "${PMA_MYSQL_PORT}"
        restart: "${PMA_RESTART}"
        depends_on:
            - mysql

        ports:
            - "${PMA_UI_PORT}:80"
        volumes:
            - "pma-data:/etc/phpmyadmin/config.user.inc.php"
        networks:
            - tirgannet
        # platform: "linux/amd64"
        links:
            - mysql
